### ISSUE TITLE
How to call the "thing" that uniquely identifies transactions

### ISSUE THREAD

**Issue by rbrunner7** [seraphis-migration/wallet3#14]
As we well know the Monero codebase uses a hash over the bytes of a transaction as the "thing" that is used to uniquely identify the transaction.

Variables and parameters that hold this are not consistently named. It's a race between `id` and variants like e.g. `txid` on the one side and `hash`, `tx_hash`, `h` or similar on the other side.

I would be glad if we could agree and standardize on one or the other for the Seraphis wallet.

Personally I currently lean towards `id`. I think a sematic name that tells what something is beats a name that tells in a very technical way how it was calculated and relies on my knowledge that hashes serve to identify transactions.

**Comment by UkoeHB** [comment]
I prefer 'transaction id' if I have to choose, but I also like 'tx hash' because it reinforces that it is a hash of the entire tx.

**Comment by One-horse-wagon** [comment]
"Transaction id" is pretty much settled on in the cryptosphere.  I like the shortened version--txid--as it would be widely understood by neophytes.

**Comment by ghost** [comment]
I support the use of id. I think what it actually is under the hood is better kept abstracted away from its name.

**Comment by rbrunner7** [comment]
Seen as decided (we use *id* in Seraphis wallet coding) after discussion in the first workgroup meeting
