### ISSUE TITLE
Petition to avoid the term "transfer" in all new wallet programming

### ISSUE THREAD

**Issue by rbrunner7** [seraphis-migration/wallet3#18]
The code of `wallet2`, the RPC interface as implemented by `monero-wallet-rpc`, the CLI wallet commands, all use the term *transfer*. It looks harmless enough, and after all making transfers is one of the core task of a wallet, so why shouldn't data structures and commands use the term *transfer*?

The main trouble as I see it is that there is more than 1 thing that can get "transferred". There are at least two: transactions and outputs. The term *transfer* won't tell you clearly which it is, and if wallet devs are not very careful and disciplined, they won't consistently use *transfer* either only for transactions or only for outputs which can lead to confusion.

Case in point: The commands of the CLI wallet. Assume you received a (somewhat unusual) transactions with 3 outputs all directed at the wallet. The command `show_transfers` will only show a single line for that transaction, so the transfers here are transactions. The command `incoming_transfers` however will show three lines, so the transfers here must be outputs.

There is not only the problem of possible confusion between transactions and outputs. If you let *transfer* always mean *output* and never transaction, you still have two terms for the same thing which again can lead to confusion. While `incoming_transfers` shows you all the outputs that the wallet controls, the command to display all the unspent outputs together with some graph is not called `unspent_transfers`, but `unspent_outputs`.

**Comment by UkoeHB** [comment]
If the semantics of CLI commands change, then it makes sense to change the terminology to avoid confusion.

**Comment by rbrunner7** [comment]
To clarify futher:

I chose the example of CLI wallet commands to show the problems of using the term *transfer* because that's a particularly striking example of confusion, and is easy to explain as well.

My main aim however are the .h and .cpp files that will make up the implementation of the new Seraphis wallet. There I would like us all to avoid the term *transfer*. So no `transfer_details` like `wallet2` has it [here](https://github.com/monero-project/monero/blob/fc907a957078cae2dc68348886a33363848dd089/src/wallet/wallet2.h#L326) now (data about a single output), or `unconfirmed_transfer_details` [here](https://github.com/monero-project/monero/blob/fc907a957078cae2dc68348886a33363848dd089/src/wallet/wallet2.h#L469) (partial data about a transaction).

**Comment by UkoeHB** [comment]
Well in those cases there is already `SpTxProposal`, `SpInputProposal`, `LegacyInputProposal`, `SpPartialTx`, etc. in `tx_builder_types.h` and `tx_legacy_builder_types.h` (and `tx_builder_types_multisig.h`).

**Comment by One-horse-wagon** [comment]
I agree on avoiding the term transfer.  It is confusing.

**Comment by rbrunner7** [comment]
Seen as decided (we agreed to mostly avoid *transfer*) after discussion in the first workgroup meeting
