### ISSUE TITLE
Shall we introduce Polyseed together with Seraphis and Jamtis?

### ISSUE THREAD

**Issue by rbrunner7** [seraphis-migration/wallet3#20]
There is a new and improved seed scheme waiting for use in Monero called *Polyseed*, as a successor to standard Monero 25 word seeds. You find info about it in our wiki [on this page](https://github.com/seraphis-migration/strategy/wiki/Polyseed). So far Feather Wallet is the only Monero wallet using it.

As written on the linked info page there is no technical requirement to use it for Seraphis and Jamtis: We could continue to use the "old" seeds. On the other hand, from a psychological and UX point of view, the hardfork to Seraphis looks like a good time to introduce a new seed scheme: If so many things change people have to re-learn and re-orient anyway and could probably "digest" a bit more change without problems.

This is merely the project to implement a new core wallet, and as such cannot really force wallet apps / wallet app writers to support Polyseed in their UI, but if the wallet fully supports Polyseed and puts everything within easy reach for wallet app writers, and if we promote the idea of Polyseed introduction with the Seraphis hardfork, it will probably work out and we can pull the rest of the ecosystem along.

Opinions? Additional arguments or votes pro or contra?

**Comment by rbrunner7** [comment]
I myself am strongly in favor of this. For 5 years already I witness all those problems with wrong restore heights after restore from seed on Reddit. Those would finally stop with Polyseed and its integrated "wallet birthday" info. Futhermore, Polyseed with its feature bits is much more future-proof than our current seeds.

Without Seraphis on the horizon I would probably seriously consider to start implementing it in `wallet2`, the CLI and the GUI wallet myself ...

**Comment by UkoeHB** [comment]
I think it's a good idea to plan on Polyseed being the default for new seraphis wallet entropy. The wallet implementation itself should be agnostic to where the restore height comes from (set it as an initialization parameter), and agnostic to the 'signing engine' (the default signing engine would just be a C++ class that records private keys `{k_m, k_vb}` similar to the current `cryptonote::account` stuff, but alternative engines would be hardware wallets, etc.).

**Comment by nahuhh** [comment]
@tobtoht has said he was soon going to PR polyseed to the current release (v16/v18.*.*). I'd imagine it would be the default moving forward (and eventually into seraphis)

**Comment by rbrunner7** [comment]
Interesting, didn't know. Will be interesting to see how the community and the ecosystem react!

**Comment by rbrunner7** [comment]
With the news that Feather Wallet dev @tobtoht will PR a Polyseed integration sooner or later to the Monero mainline code after using Polyseed for quite a while already in their wallet, the question asked by this issue is probably moot.
