### ISSUE TITLE
Prototype and next steps

### ISSUE THREAD

**Issue by DangerousFreedom1984** [seraphis-migration/wallet3#23]
Hello guys, I would like to open a discussion about the seraphis wallet implementation based on some concrete stuff as I have now a really poor/simple prototype that we could use as a model for the discussion. I have basically shrinked wallet2 and simplewallet to the most basic functions to generate/store/load a wallet and added the necessary functions to make it in the Jamtis/Seraphis standards. You can compile [this](https://github.com/DangerousFreedom1984/seraphis_lib/tree/simple_prototype/) code with [these](https://github.com/UkoeHB/monero/compare/seraphis_lib...DangerousFreedom1984:seraphis_lib:simple_prototype) modifications from koe's seraphis_lib and run the ./monero-jsp binary generated. Notice that it is far from being the first commit (which I expect to do in a couple weeks) but it (hopefully) illustrates the basic ideas.

I appreciate any thought on any of these issues.

1) Design choice. Currently wallet2 and simplewallet are the big two beasts when we talk about the Monero wallet. There are a few classes but almost no modularity. I don't think it is performing bad but it is definitely hard to read and understand what is going on. I believe we could do a bit better and introduce some modularity by separating the methods into some groups like in the figure below. Basically I would like to have classes (or only namespaces maybe) that groups these methods for organizational purposes and keep only the program flow and all the important private variables at Wallet3.
![class diagram](https://user-images.githubusercontent.com/98208928/198821968-22b16fe7-819e-4401-a512-226f037e9167.png)

2) Naming convention. I'm using the namespace jsw (jamtis-seraphis-wallet) for all the classes, Wallet3 for the main class, monero-jsp for the binary and many other conventions. I don't have any preference for naming conventions but I think it would be nice if we could start giving the appropriate terms to the respective objects in order to have the same vocabulary.

2) My biggest concern is related to manipulating properly the variable 'm_account' which is a class that holds the private keys of the wallet. In this sense I would not do differently from what is currently done. It will be a private member of Wallet3 and as soon we generate/load/save the keys, we encrypt them to avoid exposing it by someone reading the memory.

3) I really want to keep Koe's high standards in writing c++ files and avoid code and design smell. So should we also use Doxygen or something like that to better document the files?

4) Checksum. I am currently considering using blake2 or blake3 instead of Keccak for the checksum hashing as it was not yet specified at the Jamtis proposal. I have not implemented yet so any thoughts here?

5) I have cloned and modified the Base32 implementation from [this](https://github.com/tplgy/cppcodec) project, which has a MIT license, to implement our Base32 as specified by tevador's alphabet (z-Base32 without z). I have tested with many known input/outputs and it is working fine. More tests are necessary though.

7) The scope and main focus of my CCS project (in the next three months at least) will be implementing the necessary functions for generating/loading/saving a wallet and creating the necessary functions to make a transfer and generate the tx_proofs. There will be a lot of work to do to communicate with the RPC server and properly store the information on the blockchain. I might do some work in these fields as they will overlap with what I will be doing but would be great if someone could help here too.

9) Although all this work is necessary and has to be done somehow, we did not address the elephant in the room, which is how do we make a (smooth) migration into the jamtis/seraphis wallet? I am still building my understanding of the exact tasks to do but so far I see two possible scenarios.
    I) We refactor everything from wallet2 into wallet3 so when someone opens the wallet, it would be calling only methods from wallet3. 
    II) We make them independently and guide the user to the appropriate one. So we would need to make sure that:
	i) all new wallets and transactions are created in the jsp standards.
	ii) it is not possible to open a new and old wallet at the same time.
	iii) if you have an old wallet, the software would smoothly call the wallet2 functions to handle it.
	iv) if you have an old wallet that owns old inputs, wallet2 has a method to pick old inputs and create an output into the jsp standards.
	v) you can re-use your secret key to open the two different wallets, the old and the new. The wallet file should have a tag saying that it is a jsp wallet.

Personally I believe that scenario II) is much more doable. We would only need one interface that would be common to both wallet2/wallet3 so that if the user wants to load an old wallet, it knows which libraries it should use. More or less like in the figure below. Also we could think about something similar if/when we have wallet4 so the code would be already adapted for that.
![class diagram](https://user-images.githubusercontent.com/98208928/198822299-75a1ad42-ea2e-4d8a-bde4-5c1e28f9cf54.png)

Thanks for sharing your thoughts ;)

**Comment by UkoeHB** [comment]
> 1. ... I don't think it is performing bad but it is definitely hard to read and understand what is going on. I believe we could do a bit better and introduce some modularity by separating the methods into some groups like in the figure below.

`wallet2`'s problem is not just lack of modularity, it is an over-burdened API. We should really have three or more 'wallet' objects to separate normal, multisig, and view-only interfaces.

> 2. ... I'm using the namespace jsw (jamtis-seraphis-wallet) for all the classes, Wallet3 for the main class, monero-jsp for the binary and many other conventions. 

I suspect we are stuck in a 'wallet' paradigm for organizing code and interfaces. I'd recommend stepping back and asking what are all the things that need to be done, in all the different scenarios? What APIs actually need to be exposed to consumers of the library? For example, the CLI can be considered a consumer and the RPC server can be considered an exposed API. Following from that, how does the code actually need to be organized internally to service those APIs with minimal code duplication and minimal unnecessary behavior coupling?

> 3. ... My biggest concern is related to manipulating properly the variable 'm_account' which is a class that holds the private keys of the wallet.

Again, the existing account structure is overburdened - it services normal, multisig, and view-only behavior, and does not properly model non-local key storage (hardware wallets are the main example of that). This problem is probably the one I am most stumped about how to solve, because signing ceremonies are vastly different between normal/multisig/hw wallets. Perhaps a 4th variation of 'wallet' for hw spend key storage is appropriate.

It would definitely be a great advantage if we could assemble distinct interfaces easily for arbitrary use-cases, or even enable consumers of the library to build their own interfaces.

> 4. ... So should we also use Doxygen or something like that to better document the files?

It might be worth a try, but maintaining that would become an ongoing task. I also don't know if the cleaned-up header comment style I'm using will work with Doxygen (iirc they use `@param` and so on, which is ugly):
```
/**
* brief: func_name - comment
* type: type - comment   (for templates)
* param: param - comment
* inoutparam: param_inout - comment
* outparam: param_out - comment
* return: comment
*/
template <typename type>
return_type func_name(param_type param, inoutparam_type &param_inout, outparam &param_out);
```

> 5. Checksum. I am currently considering using blake2 or blake3 instead of Keccak for the checksum hashing as it was not yet specified at the Jamtis proposal. I have not implemented yet so any thoughts here?

My guess is a full-on hash algorithm will be much slower than a typical checksum algorithm. It's probably fine to use blake2b temporarily until more discussion on that can be done (we can discuss it in the MRL meetings).

> 6. I have cloned and modified the Base32 implementation from [this](https://github.com/tplgy/cppcodec) project, which has a MIT license, to implement our Base32 as specified by tevador's alphabet (z-Base32 without z). I have tested with many known input/outputs and it is working fine. More tests are necessary though.

We should use a git submodule for this at some point.

> 7. The scope and main focus of my CCS project (in the next three months at least) will be implementing the necessary functions for generating/loading/saving a wallet and creating the necessary functions to make a transfer and generate the tx_proofs.

Just to keep in mind - I'm hoping to see unit tests of all the tx proofs that are independent of any RPC calls.

> 8. II) iv) if you have an old wallet that owns old inputs, wallet2 has a method to pick old inputs and create an output into the jsp standards.

`wallet2` should be 100% deprecated after the transition. The seraphis library has fully functioning legacy balance recovery + the ability to spend legacy enotes. The only thing necessary should be migrating `wallet2` wallet file data to the new format(s) so users don't have to re-scan legacy blocks.

**Comment by rbrunner7** [comment]
I am glad to see how @DangerousFreedom1984 picks up speed!

But ... maybe I will come over as a bit pedantic, but please bear with me:

I think 5 or 6 points out of your 8 points may itself need extended discussion until we can come to a good consensus decision. If the discussion about all these many subjects takes place in a single issue, I think things get pretty tangled up and confusing pretty fast.

I propose to split it up into several, separate and pretty narrow-topic issues. I am quite sure it will take much longer until we have so many issues that oversight gets hard than it takes to get problems with "mega-issues" where many different subjects are discussed in a criss-cross way.

Thanks in advance :)

**Comment by rbrunner7** [comment]
I you want, splitting up into many issues harmonizes with the "aggressive" modularization that @UkoeHB used for his Seraphis library. There are many files with many classes instead of a few monster files, but the result is lightyears ahead in quality and future extensibility. Basically, I propose the same for our architecture and design discussions: Split it up.

**Comment by DangerousFreedom1984** [comment]
> > 1. ... I don't think it is performing bad but it is definitely hard to read and understand what is going on. I believe we could do a bit better and introduce some modularity by separating the methods into some groups like in the figure below.
> 
> `wallet2`'s problem is not just lack of modularity, it is an over-burdened API. We should really have three or more 'wallet' objects to separate normal, multisig, and view-only interfaces.

That's a very useful comment. Thanks. Yeah right now we just have one struct in the account class to handle everything. I totally agree it would be better to split the cases. I'm not fully aware of the implications though, does it also mean that ideally we would not have any conversion between normal/multisig/view-only wallets like it happens today?

> > 2. ... I'm using the namespace jsw (jamtis-seraphis-wallet) for all the classes, Wallet3 for the main class, monero-jsp for the binary and many other conventions.
> 
> I suspect we are stuck in a 'wallet' paradigm for organizing code and interfaces. I'd recommend stepping back and asking what are all the things that need to be done, in all the different scenarios? What APIs actually need to be exposed to consumers of the library? For example, the CLI can be considered a consumer and the RPC server can be considered an exposed API. Following from that, how does the code actually need to be organized internally to service those APIs with minimal code duplication and minimal unnecessary behavior coupling?

Yeah, it is a huge task to satisfy all the needs. But I agree that we should at least map the problem and make sure I (we) are attacking one specific subject at a time and that these efforts wouldn't be wasted or needed to be replicated. I'm not planning to do anything related to the RPC server but as I said my work may depend on defining some inputs/outputs that depends on that. I hope we could have more people and better structure this.

> > 3. ... My biggest concern is related to manipulating properly the variable 'm_account' which is a class that holds the private keys of the wallet.
> 
> Again, the existing account structure is overburdened - it services normal, multisig, and view-only behavior, and does not properly model non-local key storage (hardware wallets are the main example of that). This problem is probably the one I am most stumped about how to solve, because signing ceremonies are vastly different between normal/multisig/hw wallets. Perhaps a 4th variation of 'wallet' for hw spend key storage is appropriate.
Awesome that you pointed that.

> It would definitely be a great advantage if we could assemble distinct interfaces easily for arbitrary use-cases, or even enable consumers of the library to build their own interfaces.
> 
> > 4. ... So should we also use Doxygen or something like that to better document the files?
> 
> It might be worth a try, but maintaining that would become an ongoing task. I also don't know if the cleaned-up header comment style I'm using will work with Doxygen (iirc they use `@param` and so on, which is ugly):
> 
> ```
> /**
> * brief: func_name - comment
> * type: type - comment   (for templates)
> * param: param - comment
> * inoutparam: param_inout - comment
> * outparam: param_out - comment
> * return: comment
> */
> template <typename type>
> return_type func_name(param_type param, inoutparam_type &param_inout, outparam &param_out);
> ```

Yeah, on top of the name conventions/organization that you are using, I will try to at least write a few words for each function. It looks better than nothing to me.

> > 5. Checksum. I am currently considering using blake2 or blake3 instead of Keccak for the checksum hashing as it was not yet specified at the Jamtis proposal. I have not implemented yet so any thoughts here?
> 
> My guess is a full-on hash algorithm will be much slower than a typical checksum algorithm. It's probably fine to use blake2b temporarily until more discussion on that can be done (we can discuss it in the MRL meetings).
Agree.

> > 6. I have cloned and modified the Base32 implementation from [this](https://github.com/tplgy/cppcodec) project, which has a MIT license, to implement our Base32 as specified by tevador's alphabet (z-Base32 without z). I have tested with many known input/outputs and it is working fine. More tests are necessary though.
> 
> We should use a git submodule for this at some point.

A submodule wouldn't work now as I modified their library to cope with the z-base32 (but we have replaced z for 2). We could either make a PR in their library and use it as a submodule or we could clean the main functions and create a single header base32.h/base32.cpp like we have for the base58. I think it would be easier.

> > 7. The scope and main focus of my CCS project (in the next three months at least) will be implementing the necessary functions for generating/loading/saving a wallet and creating the necessary functions to make a transfer and generate the tx_proofs.
> 
> Just to keep in mind - I'm hoping to see unit tests of all the tx proofs that are independent of any RPC calls.

Consider that I'm planning to do it. The past month I got used to the libraries and made some parallel implementations of the crypto of seraphis so now I see how difficult it will be and also I made this poor prototype to have a structured/concrete plan on my next tasks. I will be doing it towards december/january.

> > 8. II) iv) if you have an old wallet that owns old inputs, wallet2 has a method to pick old inputs and create an output into the jsp standards.
> 
> `wallet2` should be 100% deprecated after the transition. The seraphis library has fully functioning legacy balance recovery + the ability to spend legacy enotes. The only thing necessary should be migrating `wallet2` wallet file data to the new format(s) so users don't have to re-scan legacy blocks.

I don't agree with this take. So if wallet2 is completely deprecated it means that besides the review of the seraphis wallet, we would need to review a complete implementation of wallet2 again? How do you see this happening? My proposal was to go in the direction where we have an interface to deal with old/new wallets differently but smoothly.

**Comment by rbrunner7** [comment]
Sorry to get a bit blunt, but I close this issue now. My eyes hurt from comments that are already indented/quoted 3 levels deep. I understand that @DangerousFreedom1984 is on the run with much enthusiasm, but we have to switch gears down a bit to stay orderly.

Next I will open a new issue about the subject of completely deprecating `wallet2` which seems to shape up as the most important topic that this multi-topic issue touches.
