### ISSUE TITLE
Re-implement RPC-Pay or not?

### ISSUE THREAD

**Issue by rbrunner7** [seraphis-migration/wallet3#3]
*RPC-Pay* is a wallet and Monero wallet RPC feature introduced in 2019 as a means to pay with hashes for the services provided by remote nodes to Monero wallet clients. An article describing it is [here](https://www.monerooutreach.org/stories/RPC-Pay.html), the commit with technical info as commit message [here](https://github.com/monero-project/monero/pull/5357/commits/2899379791b7542e4eb920b5d9d58cf232806937).

The system needed a considerable amount of code to implement. That code is not very complex however.

It's certainly an innovative approach, and the initial enthusiasm for it was considerable. Monero mining hashes as something like a second lightweight currency within the Monero ecosystem certainly has potential, in theory, and it can gently nudge people towards using their own daemons which for the good of the network they should in many situations.

Today however `monero-wallet-cli` and  `monero-wallet-rpc` are still the only Monero wallets that implement the feature, and no plans visible to extend it to other wallets. I never heard about somebody successfully setting up a remote daemon with RPC-Pay active and people connecting to it instead of connecting to one of the many "free" as ever remote daemons that are around. I guess nowadays pretty few people even know that this exists.

In the light of all this, and with a full wallet rewrite and possibly also a full rewrite of `monero-wallet-rpc` on top of `wallet3` instead of `wallet2` with a new "unified interface", there is of course the question whether to re-implement RPC-Pay.

Personally at the moment I would propose to keep such a re-implementation in mind and try to not make it hard while implementing the new infrastructure, but not actually making it part of the first version.

**Comment by UkoeHB** [comment]
RPC-Pay should be a standalone feature that the wallet doesn't need to know about. The wallet should be agnostic as to where its RPC connection comes from, whether that's directly to a local RPC, via simple free remote node, or via an RPC-Pay intermediary.

**Comment by rbrunner7** [comment]
There was a discussion about the feature on the \#monero-dev IRC channel, as it is part of the current Monero codebase i.e. pre-Seraphis, and nobody really voted for the feature anymore.

See log here: https://libera.monerologs.net/monero-dev/20230127#c196498
